FROM node:24-alpine
WORKDIR /app
COPY package*.json ./
COPY api/package.json api/package.json
COPY client/package.json client/package.json
RUN npm ci
COPY . .
EXPOSE 5173
CMD ["npm","run","dev","-w","client"]

