export const ENV_KEYS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  DATABASE_URL: 'DATABASE_URL',
  CLIENT_ORIGIN: 'CLIENT_ORIGIN',
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  TEST_DATABASE_URL: 'TEST_DATABASE_URL',
} as const;
